// <auto-generated />
namespace PImage.Category.Service.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Properties_Checked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Properties_Checked));
        
        string IMigrationMetadata.Id
        {
            get { return "201502261935083_Properties_Checked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
