//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PImage.Category.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsView
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int SubCategoryID { get; set; }
        public string SubCategoryDescription { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string FieldDescription { get; set; }
        public Nullable<int> FieldOrder { get; set; }
        public string Value { get; set; }
    }
}
