//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PImage.Category.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public int FieldsId { get; set; }
        public string Value { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Field Field { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
